name: egu_industry
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-311.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.5
  intl: ^0.18.0
  get_storage: ^2.1.1
  flutter_svg: ^2.0.2
  dio: ^5.0.1
  font_awesome_flutter: ^10.4.0
  carousel_slider: ^4.1.1
  step_progress_indicator: ^1.0.2
  url_launcher: ^6.1.3
  http: ^1.0.0
  flutter_inappwebview: ^5.7.2+3
  table_calendar: ^3.0.9
  flutter_holo_date_picker: ^1.1.2+1
  file_picker: ^5.2.0+1
  flutter_datetime_picker_plus: ^2.0.1
  printing: ^5.11.0
  flutter_simple_bluetooth_printer: ^0.1.4

  fluttertoast: ^8.1.1
  home_widget: ^0.3.0
  bluetooth_print: ^4.3.0
  permission_handler: ^10.4.3
  keyboard_service: ^2.0.2
  pdfx: ^2.4.0
  pdf: ^3.10.4
  image: ^4.1.3
  loading_animation_widget: ^1.2.0+4
  dropdown_button2: ^2.3.9
  pluto_grid: ^7.0.2
  flutter_local_notifications: ^13.0.0
  ##### ------------------------- flutter_foreground_task + ì¢…ì†
  plugin_platform_interface: ^2.1.5
  platform: ^3.1.1
  ##shared_preferences: ^2.2.0
  flutter_foreground_task: ^6.1.2
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  qr_flutter: ^4.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  flutter_launcher_icons: ^0.12.0


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/app/

flutter_icons:
  ios: true
  android: true
  image_path: "assets/app/29-2.png"
  remove_alpha_ios: true


